### ISSUE TITLE
gRPC core is considering moving to C++ for implementation

### ISSUE THREAD

**Issue by ctiller** [Juniper/grpc-c#1]
We'd be keeping a C89 public interface, and have strict rules in place for avoiding a libstdc++ dependency, but would require a C++11 compiler to compile core. I'd be interested in getting feedback on how this affects your project.

RFC is here: https://github.com/grpc/proposal/pull/21

**Comment by ajhai** [comment]
As long as the public interfaces for grpc_ and gpr_ libs do not change, this library is not effected. Applications using this library link with libgrpc and libgpr. However, one of the reasons for applications to use libgrpc-c instead of libgrpc++ and generated C++ code is compiler support for C++11 in their environment. If gRPC core requires a compiler with C++11 support, they will be stuck with older gRPC release till they migrate to a latest compiler (which they should eventually). But this project will not be effected by this change. Thanks for reaching out.
